openapi: 3.0.1
info:
  title: Game of Thrones API
  description: A Game of Thrones character and continent information service.
  contact:
    name: ThronesApi.com
    url: https://ThronesApi.com
  version: v2
paths:
  /api/v2/Characters:
    get:
      tags:
        - Characters
      summary: Returns all the characters.
      description: GET api/characters
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CharacterModel'
    post:
      tags:
        - Characters
      summary: Change a character's info.
      requestBody:
        description: The updated information on the character.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CharacterModel'
          text/json:
            schema:
              $ref: '#/components/schemas/CharacterModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CharacterModel'
      responses:
        '200':
          description: Success
  /api/v2/Characters/{id}:
    get:
      tags:
        - Characters
      summary: Returns a specific character, by id.
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterModel'
components:
  schemas:
    CharacterModel:
      type: object
      properties:
        id:
          type: integer
          description: A unique number that identifies this character.
          format: int32
        firstName:
          type: string
          description: The character's first name.
          nullable: true
        lastName:
          type: string
          description: The character's last name.
          nullable: true
        fullName:
          type: string
          description: The First + Last name of the character.
          nullable: true
        title:
          type: string
          description: The character's formal title.
          nullable: true
        family:
          type: string
          description: The character's family name.
          nullable: true
        image:
          type: string
          description: The character's picture filename
          nullable: true
        imageUrl:
          type: string
          description: The character's picture url
          nullable: true
      additionalProperties: false
      description: Information about the character.
